In [3]:
import numpy as np

testarray = np.asarray([[1,2,3],[3,4,5],[5,6,7],[11,10,11]])
testarray

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [11, 10, 11]])

In [4]:
testarray.shape

(4, 3)

In [5]:
def range(x, axis=0):
    return np.max(x, axis=axis) - np.min(x, axis=axis)
range(testarray)

array([10,  8,  8])

In [6]:
A = np.random.randint(5, size=(10,3))
print(A)

idx = np.random.randint(10, size=2)
print(idx)

print(A[idx,:])

[[0 2 2]
 [2 3 0]
 [1 1 2]
 [1 3 2]
 [4 1 4]
 [2 3 4]
 [1 2 0]
 [2 3 2]
 [3 0 4]
 [3 0 1]]
[2 0]
[[1 1 2]
 [0 2 2]]


In [7]:
#for non-replacement

A[np.random.choice(A.shape[0], 2, replace=False), :]

array([[2, 3, 4],
       [0, 2, 2]])

In [12]:
mask = np.random.choice([False, True], len(A), p=[0.75, 0.25])
A[mask]

array([[2, 3, 0],
       [1, 1, 2],
       [1, 2, 0]])